### ISSUE TITLE
final todo before merge

### ISSUE THREAD

**Issue by martin-raden** [Fulanko/IntaRNA#13]
## check cases with extreme correction term differences in heuristic ensemble mode

```
 --> rm -f tmp.log; ./src/bin/IntaRNA  --outMode=D -q gtgcggcctgaaaaacagtgctgtgcccttgtaactcatcataataatttacggcgcagccaagatttccctggtgttggcgcagtattcgcgcaccccggtctagccggggtcatttttt -t AAGTATTTTTCAGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGCTTCTGAACTGGTTACCTGCCGTGAGTAAATTAAAATTTTATTGACTTAGGTCACTAAATACTTTAACCAATATAGGCATAGCGCACAGACAGATAAAAATTACAGAGTACACAACATCCATGAAACGCATTAGCACCACCATTACCACCACCATCACCATTACCACAGGTAACGGTGCGGGCTGACGCGTACAGGAAACACAGAAAAAAGCCCGCACCT --mode=H --model=E
# DEBUG :  unbalanced correction : correctionTerm 7.64051e+10 > 0.00129095 hybridZ(i)
# DEBUG :  unbalanced correction : correctionTerm 2.12634e+13 > 0.00129095 hybridZ(i)
# DEBUG :  unbalanced correction : correctionTerm 4.50259e+23 > 0.00129095 hybridZ(i)
# DEBUG :  unbalanced correction : correctionTerm 2.59366e-17 > 4.51799e-19 hybridZ(i)
# DEBUG :  unbalanced correction : correctionTerm 6.85361e+29 > 0.00129095 hybridZ(i)
# DEBUG :  unbalanced correction : correctionTerm 2478.49 > 0.00129095 hybridZ(i)
# DEBUG : Overall Z = 2.82427e+06
# DEBUG : Overall E = -9.15
```

## non-seed Eens variants
copy and adapt of
- PredictorMaxProb4d = PredictorMfeEns4d (trace = addSeeds())
- PredictorMfe2d  = PredictorMfeEns2d (no trace)
- PredictorMfe2dHeuristic = PredictorMfeEns2dHeuristic (no trace)
- check and ensure:
  - overall Eens : PredictorMfeEns4d == PredictorMfe2d  < PredictorMfe2dSeed

**Comment by Fulanko** [comment]
implemented non-seed Eens variants

**Comment by martin-raden** [comment]
- add check to constructor of seedExtEns if key-generation is within size_t boundaries (call one static function from somewhere)

- make key-generation function static

**Comment by martin-raden** [comment]
merged into BackofenLab/IntaRNA dev branch

please pull recent version of dev and continue development there. seed-extension branch can be deleted?!

**Comment by martin-raden** [comment]
@Fulanko : is da noch was offen? wenn nicht, kannst die issue zumachen...
