### ISSUE TITLE
seed-extension implementation

### ISSUE THREAD

**Issue by martin-raden** [Fulanko/IntaRNA#2]
## theory first
- latex document mit
 - recursion + ggf bildchen wie man für gegebenen seed optimale extension ausrechnet
    - seed boundaries si1,sj1, si2,sj2
    - interaction boundaries i1..j1  i2..j2
    - interior loop energy E(..) und seed energy Eseed sowie ED penalties
  - 4d matrix variante (exact)
  - 2d matrix variante (exact)
  - 2d matrix variante (heuristic)
- wenn möglich in eigenes repo mit aktuellem pdf :)

**Comment by martin-raden** [comment]
## implementation
- extend PredictorMfe2dSeed, da PredictorMfe2d::fillHybrid() schon EL implementiert
- impl ER computation (eg `fillHybrid_right()`) und store table
- in predict():
  - compute seeds
  - iterate all seeds:
    - compute EL + ER
    - call updateOptimum() for all ij boundary combinations (compute energy sums EL+Eseed+ER)
- traceback(): 
  - teste alle seeds im range
  - liefere traceback für den ersten seed mit gleicher interaction energy

**Comment by Fulanko** [comment]
Die predict funktion ist implementiert.
Der Predictor läuft auch wieder durch (--mode X), allerdings fehlt noch der Traceback.

**Comment by martin-raden** [comment]
test mit verschiedenen q/t inputs vs
`./src/bin/IntaRNA -m M --outMode D -n 5 --outOverlap=B`

**Comment by martin-raden** [comment]
@Fulanko das sollte abgeschlossen sein oder?
