### ISSUE TITLE
partitition function variants ..

### ISSUE THREAD

**Issue by martin-raden** [Fulanko/IntaRNA#6]
... for ensemble energy statt minimal energy

sprich falls wir langeweile haben:
- seed extension predictoren duplizieren in `PredictorMfeEns2dSeedExtension*`
- datenmatrix auf `Z_type` umstellen
- summierung von energien durch multiplikation von `energy.getBW( energy )` ersetzen
- minimieren durch summieren ersetzen (liefert Z aller interactions mit aktuellen left/right bounds)
- updateMinima() mit `energy.getE( Z wert )` aufrufen
- im traceback nur die seed base pairs tracen und fertig

**Comment by Fulanko** [comment]
Implemented
